version: 2
updates:
- package-ecosystem: github-actions
  directories:
  - /
  patterns:
  - '*'
  multi-ecosystem-group: routine
multi-ecosystem-groups:
  routine:
    schedule:
      interval: weekly
      day: monday
