version: 2
updates:
  - package-ecosystem: github-actions
    directories: ["/"]
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      routine:
        applies-to: version-updates
        patterns: ["*"]
